#!/bin/sh -eu
#
# Debianize given packages and update them to PPA
# For Debian wheezy we use our own server.
# There are no words to describe all this ugliness.

package () {
    echo Build number $1 for $2
    sed -i "s/^\(haskell-stratum-tool ([.0-9]*\)[-a-z0-9]*) [a-z0-9]*/\1-$2$1) $2/" debian/changelog
    dpkg-buildpackage -S
}

reset_timer () {
    touch debian/startflag
}

find_new () {
    # Find files .changes files created after startflag file and upload them
    find .. -maxdepth 1 -name "$1" -and -cnewer debian/startflag -print0
}

if test $# -ne 1; then
    echo Build number must be given for this version >&2
    exit 1
fi

if ! test -e debianize; then
    echo Must be run in the same directory as the package >&2
    exit 1
fi

rm -rf debian/
cabal-debian '--maintainer=Joel Lehtonen <joel.lehtonen@koodilehto.fi>' --default-package stratum-tool

# Build for Launchpad 
reset_timer
for DISTRO in precise trusty utopic; do package $1 $DISTRO; done
find_new '*.changes' | xargs -0 dput ppa:zouppen/stratum-tool 

# Build for Debian Wheezy using my guerilla build server :-D Please
# note ssh agent forwarding. It uses rsync down there with my privileges.
reset_timer
package $1 wheezy
ssh -Ae none moskova cloudbuild <`find_new '*.tar.gz'`
